<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\**" />
    <Compile Remove="Services\**" />
    <Compile Remove="Tools\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <EmbeddedResource Remove="Services\**" />
    <EmbeddedResource Remove="Tools\**" />
    <None Remove="Interfaces\**" />
    <None Remove="Services\**" />
    <None Remove="Tools\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VianaHub.Global.Identity.Domain\VianaHub.Global.Identity.Domain.csproj" />
  </ItemGroup>
</Project>
