namespace VianaHub.Global.Identity.Application.Dto.Response.Job;

public record JobDetailResponse(
    int Id,
    int TenantId,
    string Tenant,
    string JobCategory,
    string JobName,
    string Description,
    string JobPurpose,
    string JobType,
    string JobMethod,
    string CronExpression,
    string TimeZoneId,
    bool ExecuteOnlyOnce,
    int TimeoutMinutes,
    int Priority,
    string Queue,
    int MaxRetries,
    string JobConfiguration,
    bool IsSystemJob,
    string HangfireJobId,
    DateTime? LastRegisteredAt,
    DateTime? NextExecution,
    DateTime? LastExecution,
    string LastExecutionStatus,
    int Status,
    bool IsActive);